FROM python:3.10

RUN apt-get update && apt-get install -y tesseract-ocr

WORKDIR /app
COPY . .
RUN pip install -r requirements.txt

CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "10000"]
